export default {
  SET_USEROAUTH: 'SET_USEROAUTH',
  INIT_USEROAUTH: 'INIT_USEROAUTH',
  CLEAR_USEROAUTH: 'CLEAR_USEROAUTH',
  SET_USERINFO: 'SET_USERINFO',
  INIT_USERINFO: 'INIT_USERINFO',
  CLEAR_USERINFO: 'CLEAR_USERINFO',
  INIT_STORE: 'INIT_STORE',
  CLEAR_STORE: 'CLEAR_STORE',
  SET_LOADING: 'SET_LOADING',
}
